---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-db-mongodata
  namespace: dev
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
 # storageClassName: gold
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  namespace: dev
  labels:
    name: orders-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: orders-db
  template:
    metadata:
      labels:
        name: orders-db
    spec:
      containers:
      - image: mongo
        name: orders-db
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: orders-db-mongodata
      restartPolicy: Always
      volumes:
      - name: orders-db-mongodata
        persistentVolumeClaim:
          claimName: orders-db-mongodata
---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: dev
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    name: orders-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-db-mongodata
  namespace: staging
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
#  storageClassName: gold
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  namespace: staging
  labels:
    name: orders-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: orders-db
  template:
    metadata:
      labels:
        name: orders-db
    spec:
      containers:
      - image: mongo
        name: orders-db
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: orders-db-mongodata
      restartPolicy: Always
      volumes:
      - name: orders-db-mongodata
        persistentVolumeClaim:
          claimName: orders-db-mongodata
---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: staging
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    name: orders-db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orders-db-mongodata
  namespace: production
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
#  storageClassName: gold
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-db
  namespace: production
  labels:
    name: orders-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: orders-db
  template:
    metadata:
      labels:
        name: orders-db
    spec:
      containers:
      - image: mongo
        name: orders-db
        ports:
        - containerPort: 27017
        resources: {}
        volumeMounts:
        - mountPath: /data/db
          name: orders-db-mongodata
      restartPolicy: Always
      volumes:
      - name: orders-db-mongodata
        persistentVolumeClaim:
          claimName: orders-db-mongodata
---
apiVersion: v1
kind: Service
metadata:
  name: orders-db
  namespace: production
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    name: orders-db
